### ISSUE TITLE
Prevent not-valid values in output CSS

### ISSUE THREAD

**Issue by hudochenkov** [simonsmith/postcss-property-lookup#1]
In test/fixtures/out/default.css invalid property is going to output. Maybe better option is not include invalid property and show warning in terminal? [Plugin](https://github.com/davidtheclark/postcss-log-warnings) for console warnings.

```
.Test2 {
  margin-left: 400px;
  margin-right: 400px;
}
```

**Comment by simonsmith** [comment]
Yeah, agreed that it's a nicer solution. Will look into it

**Comment by hudochenkov** [comment]
Thank you!

It still produce invalid CSS. `top: ;` isn't valid. Maybe it's a good idea. You look at devtools why element is not like it should be and immediately see what is wrong.

**Comment by simonsmith** [comment]
Yeah, so I decided to see how Stylus handled it and match that. It will still send a warning though so it should help users see where the errors are. Will push a new release now
