### ISSUE TITLE
Publish fixes on PostCSS 4.x path

### ISSUE THREAD

**Issue by jedmao** [simonsmith/postcss-property-lookup#12]
For those, like me, who are still "stuck" on the PostCSS 4.x path, because of certain plugins not yet supporting PostCSS 5.x, I could really use the 4.x version of this plugin (for now); however, there have been some fixes of recent that are not on the 4.x path.

Would you consider creating a postcss-4.0 branch, to which I can submit a PR that has all the new fixes?

Basically, I would just take the existing master branch, change the PostCSS dependency to 4.x and replace `root.walkRules()` with `root.eachRule()`. Perhaps it can be pushed as postcss-property-lookup version 0.4.0.

How does that sound?

**Comment by simonsmith** [comment]
Sounds like an excellent idea yeah. I hadn't been following the recent developments of PostCSS all that closely so kinda botched this a bit.

**Comment by jedmao** [comment]
Can I get you to create a branch then so I can submit a PR to that branch?

**Comment by simonsmith** [comment]
I'll make you a collaborator, will be easier to manage PRs that way :)

**Comment by jedmao** [comment]
@simonsmith I can `npm publish` from the [postcss-4.x](https://github.com/simonsmith/postcss-property-lookup/tree/postcss-4.x) branch if you `npm adduser jedmao`. Do you normally publish the `.tar.gz` file or directly from the project root?

**Comment by simonsmith** [comment]
I've published it, can be installed with a tag:

`npm install postcss-property-lookup@postcss-4.x`

We should probably add that to the release notes/README

**Comment by jedmao** [comment]
Thanks! I've added 2 PRs for both version paths.

**Comment by simonsmith** [comment]
Great stuff, thanks for your help again!
