### ISSUE TITLE
Error on lookup of same property

### ISSUE THREAD

**Issue by Ser-Gen** [simonsmith/postcss-property-lookup#21]
We can make this plugin more foolproof.
If I refer to same property, I need to get proper error.

``` pcss
.elem {
  color: @color;
}
```

Now I get meaningless `Maximum call stack size exceeded`.

**Comment by jedmao** [comment]
Would it make sense to lookup the closest ancestor `@color` prop in this scenario?

**Comment by radziksh** [comment]
@jedmao it will be perfect sense for us!
